services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env.production

  bcapi:
    build: ./api
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.production
    depends_on:
      - mongodb

  bcwebsite:
    build: ./website
    restart: always
    ports:
      - 80:80
    depends_on:
      - bcapi
      
  bcadmin:
    build: ./admin
    restart: always
    ports:
      - 81:80
    depends_on:
      - bcapi
volumes:
  mongodb_data: