version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

  backend:
    build: ./backend
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.production
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  mongodb_data: