@apiURL = http://192.168.3.62:3000

### User Sign In
# @name authTokenRequest
POST  {{apiURL}}/auth/signIn
Content-Type: application/json

{
    "email": "medeirosleandro1982@gmail.com",
    "password": "itapoa1234"
}

###
@authToken = {{authTokenRequest.response.body.token}}

### GET users
GET {{apiURL}}/users
Authorization: Bearer {{authToken}}
content-yype: application/json


### Add User
PUT  {{apiURL}}/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "email": "medeirosleandro1982@gmail.com",
    "password": "itapoa1234",
    "name": "Leandro",
    "active": false,
    "isAdmin": true
}

### GET user
GET {{apiURL}}/users/65dea3d1827a2b49286b02d7
Authorization: Bearer {{authToken}}
content-yype: application/json

### Update user
POST  {{apiURL}}/users/65dea3d1827a2b49286b02d7
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "email": "medeirosleandro1982@gmail.com",
    "password": "itapoa1234",
    "name": "Leandro",
    "active": true,
    "isAdmin": true
}

### Remove a User
DELETE {{apiURL}}/users/65dd4d0ff4febad942206bc7
Authorization: Bearer {{authToken}}
Content-Type: application/json
