@apiURL = http://localhost:3000

### User Sign In
# @name authTokenRequest
# @prompt email
# @prompt password
POST  {{apiURL}}/auth/signIn
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
@token = {{authTokenRequest.response.body.token}}
