@apiURL = http://localhost:3000

### Send Email
POST  {{apiURL}}/contact
Content-Type: application/json

{
    "email":"medeirosleandro1982@gmail.com",
    "subject":"teste de envio",
    "message":"testando envio de email"
}